version: '3.9'
services:

  nginx:
    container_name: fci_IFM_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - webapp
    networks:
      - default

  webapp:
    container_name: fci_IFM_webapp
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    volumes:
      - ./app/backend/src:/usr/src/app/src
      - ./app/backend/server.js:/usr/src/app/server.js
      - ./app/backend/package.json:/usr/src/app/package.json
      - ./app/backend/package-lock.json:/usr/src/app/package-lock.json
      - ./app/frontend:/usr/src/frontend
    working_dir: /usr/src/app
    command: npm run dev
    expose:
      - "8888"
    networks:
      - default
